window.SPECTRUM_CONFIG=window.SPECTRUM_CONFIG||{supabaseUrl:"https://cevylpnoexugwgygvtgu.supabase.co",supabaseKey:"sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-",crowspaceUrl:"https://crowrulesentertainment-oss.github.io/crowspace/",membershipUrl:"https://crowrulesentertainment-oss.github.io/crowspace/login.html",awardYear:2029};
const categorySeed=["Motion Pictures","Television","Streaming","Documentary","Animation","Comedy","Drama","Action","Horror","Science Fiction & Fantasy","Short Film","Music","Recording Artist","Songwriting","Music Video","Live Performance","Podcasting","Radio / Audio","Digital Creator","YouTube / Online Video","Social Media","Gaming / Esports","Voice Acting","Writing","Screenwriting","Directing","Producing","Cinematography","Editing","Production Design","Costume Design","Makeup & Hair","Visual Effects","Sound Design","Stunt Performance","Dance","Theatre","Broadway / Stage","Stand-Up","Journalism / Entertainment News","Sports Entertainment","Children & Family","Emerging Creator","Community Impact","Lifetime Achievement","CrowRules Community Choice"];
let sb=null,currentUser=null,currentConfig=null;
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function showMsg(msg,type){const e=document.querySelector("#message");if(e){e.className="notice "+(type||"");e.textContent=msg}}
async function initSpectrum(){if(window.supabase&&SPECTRUM_CONFIG.supabaseKey&&!SPECTRUM_CONFIG.supabaseKey.startsWith("YOUR_"))sb=window.supabase.createClient(SPECTRUM_CONFIG.supabaseUrl,SPECTRUM_CONFIG.supabaseKey);renderNav();if(sb){const r=await sb.auth.getSession();currentUser=r.data?.session?.user||null;updateMember(r.data?.session);sb.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;updateMember(s)})}}
function renderNav(){const n=document.querySelector("#global-nav");if(!n)return;const links=[["home.html","Home"],["categories.html","Categories"],["nominations.html","Nominations"],["pre-voting.html","Pre-Voting"],["live-voting.html","Live Voting"],["broadcast.html","Broadcast"],["winners.html","Winners"],["planning.html","Yearly Planning"],[SPECTRUM_CONFIG.crowspaceUrl,"CrowSpace"]];n.innerHTML=links.map(x=>'<a href="'+x[0]+'">'+x[1]+"</a>").join("")}
function updateMember(session){const el=document.querySelector("#member-status");if(!el)return;el.innerHTML=session?'<a class="member" href="'+SPECTRUM_CONFIG.membershipUrl+'">MEMBER • '+esc(session.user.email||"ACCOUNT")+"</a>":'<a class="member" href="'+SPECTRUM_CONFIG.membershipUrl+'">UNIVERSAL MEMBERSHIP • SIGN IN</a>'}
async function requireAuth(){if(!sb){showMsg("Spectrum is not connected to Supabase yet.","error");return null}const r=await sb.auth.getSession();if(!r.data.session){showMsg("Sign in with your Universal CrowRules Membership account to continue.","error");return null}return r.data.session.user}
async function loadCategories(){const box=document.querySelector("#category-list");if(!box)return;let cats=[];if(sb){const r=await sb.from("spectrum_categories").select("id,name,description,sort_order").order("sort_order",{ascending:true});if(!r.error)cats=r.data||[]}if(!cats.length)cats=categorySeed.map((name,i)=>({id:"seed-"+i,name,description:"Spectrum Awards entertainment category.",sort_order:i}));box.innerHTML=cats.map(c=>'<div class="card"><div class="kicker">CATEGORY</div><h3>'+esc(c.name)+'</h3><p>'+esc(c.description||"Open to eligible entertainment work and creators.")+"</p></div>").join("")}
async function loadNominationCategories(){const s=document.querySelector("#category");if(!s)return;let cats=[];if(sb){const r=await sb.from("spectrum_categories").select("id,name").order("sort_order",{ascending:true});if(!r.error)cats=r.data||[]}if(!cats.length)cats=categorySeed.map(name=>({id:name,name}));s.innerHTML=cats.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+"</option>").join("")}
async function loadNominationSubcategories(categoryId){const s=document.querySelector("#subcategory");if(!s)return;s.innerHTML='<option value="">Loading…</option>';if(!sb||!categoryId){s.innerHTML='<option value="">Select a category first</option>';return}const r=await sb.from("spectrum_subcategories").select("id,name").eq("category_id",categoryId).eq("active",true).order("sort_order");if(r.error||!r.data?.length){s.innerHTML='<option value="">No subcategories available</option>';return}s.innerHTML='<option value="">Select a subcategory</option>'+r.data.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join("")}
function submissionType(value){return ({Creator:"creator",Work:"project",Performance:"performance",Organization:"other",Community:"other"})[value]||"other"}
async function submitNomination(e){e.preventDefault();const user=await requireAuth();if(!user)return;const f=new FormData(e.target);const title=String(f.get("work_title")||f.get("nominee_name")||"Spectrum Submission").trim();const note=String(f.get("description")||"").trim();const row={user_id:user.id,category_id:f.get("category_id"),subcategory_id:f.get("subcategory_id")||null,title,description:note,submission_type:submissionType(f.get("nominee_type")),status:"submitted",submitter_note:"Nominee/Creator: "+String(f.get("nominee_name")||"").trim()};const r=await sb.from("spectrum_submissions").insert(row).select("id").single();if(r.error)showMsg(r.error.message,"error");else{showMsg("Nomination submitted to the Spectrum Awards review queue.");e.target.reset();if(r.data?.id)sessionStorage.setItem("spectrum_last_submission",r.data.id)}}
async function loadVotingConfig(){currentConfig=null;if(!sb)return null;const r=await sb.from("spectrum_voting_config").select("id,award_id,voting_status,opens_at,closes_at,eligibility,max_votes_per_category,public_results_enabled").eq("voting_status","open").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!r.error&&r.data)currentConfig=r.data;return currentConfig}
function votingOpen(c){if(!c||c.voting_status!=="open")return false;const now=Date.now();return (!c.opens_at||new Date(c.opens_at).getTime()<=now)&&(!c.closes_at||new Date(c.closes_at).getTime()>now)}
async function loadVoteSet(){const box=document.querySelector("#vote-set");if(!box)return;const c=await loadVotingConfig();if(!c||!votingOpen(c)){box.innerHTML='<div class="notice">Voting is not currently open. When the Spectrum Awards voting configuration is opened, official nominees will appear here.</div>';return}const r=await sb.from("spectrum_nominees").select("id,category_id,name,description").eq("status","official").order("name",{ascending:true});if(r.error){box.innerHTML='<div class="notice error">'+esc(r.error.message)+"</div>";return}const rows=r.data||[];if(!rows.length){box.innerHTML='<div class="notice">No official nominees have been published for the open voting round yet.</div>';return}const cats={};for(const x of rows)(cats[x.category_id]??=[]).push(x);const catIds=Object.keys(cats);let html="";for(const cid of catIds){let catName=cid;const cr=await sb.from("spectrum_categories").select("name").eq("id",cid).maybeSingle();if(!cr.error&&cr.data?.name)catName=cr.data.name;html+='<fieldset class="card vote-category"><legend>'+esc(catName)+'</legend>'+cats[cid].map(x=>'<label class="radio"><input required type="radio" name="category_'+esc(cid)+'" value="'+esc(x.id)+'" data-category="'+esc(cid)+'"><span><b>'+esc(x.name)+'</b><br><small>'+esc(x.description||"")+"</small></span></label>").join("")+"</fieldset>"}box.innerHTML=html}
async function castVote(e){e.preventDefault();const user=await requireAuth();if(!user)return;const c=currentConfig||await loadVotingConfig();if(!c||!votingOpen(c)){showMsg("Voting is not currently open.","error");return}const inputs=[...e.target.querySelectorAll('input[type="radio"]:checked')];if(!inputs.length){showMsg("Select a nominee in each category before submitting.","error");return}let failures=[];for(const input of inputs){const categoryId=input.dataset.category;const r=await sb.from("spectrum_ballots").insert({voting_config_id:c.id,user_id:user.id,category_id:categoryId,nominee_id:input.value});if(r.error)failures.push(r.error.message)}if(failures.length)showMsg(failures[0],"error");else showMsg("Your Spectrum vote has been recorded. The database enforces one ballot per category for this voting configuration.")}
async function loadWinners(){const box=document.querySelector("#winners-list");if(!box)return;if(!sb){box.innerHTML='<div class="notice">Connect Supabase to load official winners.</div>';return}const r=await sb.from("spectrum_nominees").select("id,name,description,status,category_id").eq("status","winner").order("name");if(r.error){box.innerHTML='<div class="notice error">'+esc(r.error.message)+"</div>";return}const rows=r.data||[];if(!rows.length){box.innerHTML='<div class="notice">No winners published yet.</div>';return}box.innerHTML=rows.map(x=>'<div class="item"><div><b>'+esc(x.name)+'</b><br><small>'+esc(x.description||"")+"</small></div><span class="chip">WINNER</span></div>").join("")}
function startCountdown(){const el=document.querySelector("#countdown");if(!el)return;const target=new Date("2029-12-31T20:00:00-08:00");function tick(){let d=Math.max(0,target-new Date()),s=Math.floor(d/1000),days=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);s%=60;el.textContent=days+"D "+String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}tick();setInterval(tick,1000)}
document.addEventListener("DOMContentLoaded",async()=>{const b=document.querySelector(".menu");if(b)b.addEventListener("click",()=>document.querySelector(".navlinks")?.classList.toggle("open"));await initSpectrum();await loadCategories();await loadNominationCategories();await loadWinners();startCountdown();document.querySelector("#nomination-form")?.addEventListener("submit",submitNomination);document.querySelector("#category")?.addEventListener("change",e=>loadNominationSubcategories(e.target.value));document.querySelector("#pre-vote-form")?.addEventListener("submit",castVote);document.querySelector("#live-vote-form")?.addEventListener("submit",castVote);if(document.querySelector("#pre-vote-form")||document.querySelector("#live-vote-form"))await loadVoteSet()});