window.SPECTRUM_CONFIG=window.SPECTRUM_CONFIG||{supabaseUrl:"https://cevylpnoexugwgygvtgu.supabase.co",supabaseKey:"YOUR_SUPABASE_PUBLISHABLE_KEY",crowspaceUrl:"https://crowrulesentertainment-oss.github.io/crowspace/",membershipUrl:"https://crowrulesentertainment-oss.github.io/crowspace/login.html",awardYear:2029};
const categorySeed=["Motion Pictures","Television","Streaming","Documentary","Animation","Comedy","Drama","Action","Horror","Science Fiction & Fantasy","Short Film","Music","Recording Artist","Songwriting","Music Video","Live Performance","Podcasting","Radio / Audio","Digital Creator","YouTube / Online Video","Social Media","Gaming / Esports","Voice Acting","Writing","Screenwriting","Directing","Producing","Cinematography","Editing","Production Design","Costume Design","Makeup & Hair","Visual Effects","Sound Design","Stunt Performance","Dance","Theatre","Broadway / Stage","Stand-Up","Journalism / Entertainment News","Sports Entertainment","Children & Family","Emerging Creator","Community Impact","Lifetime Achievement","CrowRules Community Choice"];
let sb=null;
function esc(v){return String(v??"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
async function initSpectrum(){if(window.supabase&&SPECTRUM_CONFIG.supabaseKey&&!SPECTRUM_CONFIG.supabaseKey.startsWith("YOUR_"))sb=window.supabase.createClient(SPECTRUM_CONFIG.supabaseUrl,SPECTRUM_CONFIG.supabaseKey);renderNav();if(sb){const r=await sb.auth.getSession();updateMember(r.data&&r.data.session);sb.auth.onAuthStateChange(function(_e,s){updateMember(s)})}}
function renderNav(){const n=document.querySelector("#global-nav");if(!n)return;const links=[["home.html","Home"],["categories.html","Categories"],["nominations.html","Nominations"],["pre-voting.html","Pre-Voting"],["live-voting.html","Live Voting"],["broadcast.html","Broadcast"],["winners.html","Winners"],["planning.html","Yearly Planning"],[SPECTRUM_CONFIG.crowspaceUrl,"CrowSpace"]];n.innerHTML=links.map(function(x){return '<a href="'+x[0]+'">'+x[1]+"</a>"}).join("")}
function updateMember(session){const el=document.querySelector("#member-status");if(!el)return;el.innerHTML=session?'<a class="member" href="'+SPECTRUM_CONFIG.membershipUrl+'">MEMBER • '+esc(session.user.email||"ACCOUNT")+"</a>":'<a class="member" href="'+SPECTRUM_CONFIG.membershipUrl+'">UNIVERSAL MEMBERSHIP • SIGN IN</a>'}
async function requireAuth(){if(!sb){showMsg("Supabase is not configured yet. Add the publishable key in SPECTRUM_CONFIG before submitting or voting.","error");return null}const r=await sb.auth.getSession();if(!r.data.session){showMsg("Sign in with your Universal CrowRules Membership account to continue.","error");return null}return r.data.session.user}
function showMsg(msg,type){const e=document.querySelector("#message");if(e){e.className="notice "+(type||"");e.textContent=msg}}
async function loadCategories(){const box=document.querySelector("#category-list");if(!box)return;let cats=[];if(sb){const r=await sb.from("spectrum_categories").select("*").eq("active",true).order("sort_order",{ascending:true});if(!r.error)cats=r.data||[]}if(!cats.length)cats=categorySeed.map(function(name,i){return{id:"seed-"+i,name:name,description:"Spectrum Awards entertainment category.",active:true}});box.innerHTML=cats.map(function(c){return '<div class="card"><div class="kicker">CATEGORY</div><h3>'+esc(c.name||c.category_name)+'</h3><p>'+esc(c.description||"Open to eligible entertainment work and creators.")+"</p></div>"}).join("")}
async function loadNominationCategories(){const s=document.querySelector("#category");if(!s)return;let cats=[];if(sb){const r=await sb.from("spectrum_categories").select("id,name").eq("active",true).order("sort_order");if(!r.error)cats=r.data||[]}if(!cats.length)cats=categorySeed.map(function(name){return{id:name,name:name}});s.innerHTML=cats.map(function(c){return '<option value="'+esc(c.id)+'">'+esc(c.name)+"</option>"}).join("")}
async function submitNomination(e){e.preventDefault();const user=await requireAuth();if(!user)return;const f=new FormData(e.target);const row={category_id:f.get("category_id"),nominee_name:f.get("nominee_name"),work_title:f.get("work_title"),nominee_type:f.get("nominee_type"),description:f.get("description"),submitted_by:user.id};const r=await sb.from("spectrum_nominations").insert(row);if(r.error)showMsg(r.error.message,"error");else{showMsg("Nomination submitted to the Spectrum Awards review queue.");e.target.reset()}}
async function loadVoteSet(round){const box=document.querySelector("#vote-set");if(!box)return;let rows=[];if(sb){const r=await sb.from("spectrum_nominations").select("*").eq("status","finalist").eq("voting_round",round).order("category_id");if(!r.error)rows=r.data||[]}if(!rows.length){box.innerHTML='<div class="notice">No published nominees are available for this round yet. The awards team can publish finalists from the Supabase admin workflow.</div>';return}box.innerHTML=rows.map(function(x){return '<label class="radio"><input required type="radio" name="nominee_id" value="'+esc(x.id)+'"><span><b>'+esc(x.nominee_name)+'</b><br><small>'+esc(x.work_title||"")+"</small></span></label>"}).join("")}
async function castVote(e,round){e.preventDefault();const user=await requireAuth();if(!user)return;const nominee=e.target.nominee_id&&e.target.nominee_id.value;if(!nominee)return;const r=await sb.from("spectrum_votes").insert({nominee_id:nominee,round:round,member_id:user.id});if(r.error)showMsg(r.error.message,"error");else showMsg("Your vote has been recorded. One vote per nominee per round is enforced by the database.")}
async function loadWinners(){const box=document.querySelector("#winners-list");if(!box)return;if(!sb){box.innerHTML='<div class="notice">Connect Supabase to load official winners.</div>';return}const r=await sb.from("spectrum_winners").select("*").eq("published",true).order("award_year",{ascending:false}).order("category_name");if(r.error){box.innerHTML='<div class="notice error">'+esc(r.error.message)+"</div>";return}box.innerHTML=(r.data||[]).map(function(x){return '<div class="item"><div><b>'+esc(x.category_name)+'</b><br><small>'+esc(x.nominee_name)+(x.work_title?" • "+esc(x.work_title):"")+'</small></div><span class="chip">'+esc(x.award_year)+"</span></div>"}).join("")||'<div class="notice">No winners published yet.</div>'}
function startCountdown(){const el=document.querySelector("#countdown");if(!el)return;const target=new Date("2029-12-31T20:00:00-08:00");function tick(){let d=Math.max(0,target-new Date()),s=Math.floor(d/1000),days=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;el.textContent=days+"D "+String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}tick();setInterval(tick,1000)}
document.addEventListener("DOMContentLoaded",async function(){const b=document.querySelector(".menu");if(b)b.addEventListener("click",function(){document.querySelector(".navlinks")?.classList.toggle("open")});await initSpectrum();await loadCategories();await loadNominationCategories();await loadWinners();startCountdown();document.querySelector("#nomination-form")?.addEventListener("submit",submitNomination);document.querySelector("#pre-vote-form")?.addEventListener("submit",function(e){return castVote(e,"pre")});document.querySelector("#live-vote-form")?.addEventListener("submit",function(e){return castVote(e,"live")});if(document.querySelector("#pre-vote-form"))await loadVoteSet("pre");if(document.querySelector("#live-vote-form"))await loadVoteSet("live")});